site_name: BasicState
site_url: https://clockworksquirrel.github.io/BasicState/
site_author: csqrl
site_description: A really simple state management solution for Roblox
repo_name: ClockworkSquirrel/BasicState
repo_url: https://github.com/ClockworkSquirrel/BasicState
google_analytics: [ "UA-145876682-4", "clockworksquirrel.github.io/BasicState" ]
copyright: ©2020 - csqrl (ClockworkSquirrel)

theme:
  name: material
  features:
    - instant
  language: en
  palette:
    primary: green
    accent: green
  font:
    code: "Fira Code"
  icon:
    logo: material/school
    repo: fontawesome/brands/github-alt

pages:
  - Home: index.md
  - Examples: example.md
  - Documentation: docs.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - toc:
      permalink: true
